//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace varastonhallinta1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Henkilöstö
    {
        public int HenkilöID { get; set; }
        public string Etunimi { get; set; }
        public string Sukunimi { get; set; }
        public string Puhelin { get; set; }
        public string Sähköposti { get; set; }
        public int RooliID { get; set; }
    
        public virtual Roolit Roolit { get; set; }
        public virtual Logins Logins { get; set; }
    }
}
