//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace varastonhallinta1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tilaukset
    {
        [Key]
        public int TilausID { get; set; }
        public Nullable<int> TuoteID { get; set; }
        public Nullable<int> Määrä { get; set; }
        public Nullable<int> AsiakasID { get; set; }
    
        public virtual Asiakkaat Asiakkaat { get; set; }
        public virtual Tuotteet Tuotteet { get; set; }
    }
}
