//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace varastonhallinta1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VarastoSaldot
    {
        public int VarastoID { get; set; }
        public Nullable<int> TuoteID { get; set; }
        public string Tuotemerkki { get; set; }
        public Nullable<int> Määrä { get; set; }
        public string VarastoPaikka { get; set; }
    
        public virtual Tuotteet Tuotteet { get; set; }
    }
}
